Section "InputClass"
	Identifier "touchpad"
	Driver "libinput"
	MatchIsTouchpad "on"
	#Option "AccelSpeed" "-0.5"
	Option "ClickMethod" "none"
	#Option "DisableWhileTyping" "1"
	#Option "HighResolutionWheelScrolling" "1"
	Option "HorizontalScrolling" "1"
	#Option "MiddleEmulation" "1"
	#Option "NaturalScrolling" "0"
	Option "ScrollPixelDistance" "50"
	Option "Tapping" "1"
EndSection
